name: "auto releases"

on:
  push:
    branches:
      - "master"

jobs:
  zip-and-release:
    name: "zip and pre-release"
    runs-on: "ubuntu-latest"  

    steps:

      - name: "Checkout source code" 
        uses: actions/checkout@v4

      - name: "Read VERSION file"
        id: getversion
        run: echo "version=ยง(cat VERSION)" >> $GITHUB_OUTPUT
      
      - name: "zip texture pack"
        uses: vimtor/action-zip@v1.2
        with:
          files: pack.png pack.mcmeta assets
          recursive: false
          dest: solariarp-resourcepack.zip

      - name: "auto release"
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          automatic_release_tag: "v${{ steps.getversion.outputs.version }}"
          title: "Release ${{ steps.getversion.outputs.version }}"
          files: solariarp-resourcepack.zip